### ISSUE TITLE
Yarn compile has error.

### ISSUE THREAD

**Issue by hobbydev71** [Uniswap/v2-core#156]
I tried `yarn compile`, but it shows the error `Invalid callback specified.`
This is the output.

yarn run v1.22.17
$ yarn clean
$ rimraf ./build/
$ waffle .waffle.json
AssertionError [ERR_ASSERTION]: Invalid callback specified.
    at wrapCallback (E:\Work\Computecoin\Uniswap\v2-core\node_modules\solc\wrapper.js:16:5)
    at runWithReadCallback (E:\Work\Computecoin\Uniswap\v2-core\node_modules\solc\wrapper.js:42:26)
    at compileStandard (E:\Work\Computecoin\Uniswap\v2-core\node_modules\solc\wrapper.js:83:14)
    at Object.compileStandardWrapper (E:\Work\Computecoin\Uniswap\v2-core\node_modules\solc\wrapper.js:90:14)
    at compile (E:\Work\Computecoin\Uniswap\v2-core\node_modules\@ethereum-waffle\compiler\dist\cjs\compileSolcjs.js:54:29) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How can I fix that?

**Comment by 0xouzm** [comment]
rm yarn.lock && node_modules and run it again
